In [1]:
import pandas as pd
import numpy as np

In [2]:
arr1 = np.array((18, 14, 23, 36))
arr2 = np.array((12, 1, 4, 7))

In [3]:
np.add(arr1, arr2)

array([30, 15, 27, 43])

In [4]:
np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.array([1, 2, 3, 4, 5, 6]).reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'New York', 'Houston']
}

# Create DataFrame
df = pd.DataFrame(data)

In [7]:
df['Age'].unique()

array([25, 30, 35, 40])

In [8]:
aggregated = df.groupby('City').agg({'Age': ['mean', 'sum', 'std', 'prod', 'count']})
print(aggregated)

              Age                         
             mean sum       std prod count
City                                      
Houston      40.0  40       NaN   40     1
Los Angeles  30.0  30       NaN   30     1
New York     30.0  60  7.071068  875     2


In [9]:
25*35

875

In [10]:
type(df['Age'].unique())

numpy.ndarray

In [11]:
np.array([1, 2, 3, 4, 5, 6]).reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
arr1 + arr2

array([30, 15, 27, 43])

In [13]:
sum(arr1, arr2)

array([103,  92,  95,  98])

In [14]:
type(np.array([18, 14, 23, 36]))

numpy.ndarray

In [15]:
type(np.array((18, 14, 23, 36)))

numpy.ndarray

In [22]:
def mnk(x_, y_):
    # Находим количество точек
    n = len(x_)
    
    # Рассчитываем необходимые суммы
    sum_x = np.sum(x_)
    sum_y = np.sum(y_)
    sum_xy = np.sum(x_ * y_)
    sum_xx = np.sum(x_ * x_)
    
    # Рассчитываем коэффициенты a и b
    a = (n * sum_xy - sum_x * sum_y) / (n * sum_xx - sum_x**2)
    b = (sum_y - a * sum_x) / n
    
    return a, b

# Пример использования
x_ = np.linspace(0, 10, 30)  # временной ряд x длиной 30 точек
y_ = 3 * x_ + 2              # временной ряд y с коэффициентами a = 3, b = 2

# Находим коэффициенты a и b
a, b = mnk(x_, y_)
print("a:", a)
print("b:", b)

a: 3.0000000000000013
b: 1.9999999999999905


In [26]:
Cars = pd.read_csv('Electric_Car.csv')

In [27]:
Cars.head()

Brand                          Model  AccelSec  TopSpeed_KmH  \
0       Tesla   Model 3 Long Range Dual Motor       4.6           233   
1  Volkswagen                       ID.3 Pure      10.0           160   
2    Polestar                               2       4.7           210   
3         BMW                            iX3        6.8           180   
4       Honda                              e        9.5           145   

   Range_Km  Efficiency_WhKm FastCharge_KmH RapidCharge PowerTrain  \
0       450              161            940         Yes        AWD   
1       270              167            250         Yes        RWD   
2       400              181            620         Yes        AWD   
3       360              206            560         Yes        RWD   
4       170              168            190         Yes        RWD   

     PlugType  BodyStyle Segment  Seats  PriceEuro  
0  Type 2 CCS      Sedan       D      5      55480  
1  Type 2 CCS  Hatchback       C      5      30000  
2  Type 2 CCS   Liftback       D      5      56440  
3  Type 2 CCS        SUV       D      5      68040  
4  Type 2 CCS  Hatchback       B      4      32997

In [30]:
Carsgroupby = Cars.groupby('Brand').agg({'PriceEuro':'mean'})
Carsgroupby

PriceEuro
Brand                     
Aiways        36057.000000
Audi          80593.666667
BMW           53145.750000
Byton         59833.333333
CUPRA         45000.000000
Citroen       40000.000000
DS            37422.000000
Fiat          36400.000000
Ford          54568.750000
Honda         34459.000000
Hyundai       36408.333333
Jaguar        75351.000000
Kia           35862.400000
Lexus         50000.000000
Lightyear    149000.000000
Lucid        105000.000000
MG            30000.000000
Mazda         32646.000000
Mercedes      61705.000000
Mini          31681.000000
Nissan        45902.125000
Opel          35350.666667
Peugeot       32021.500000
Polestar      56440.000000
Porsche      138265.800000
Renault       31268.200000
SEAT          20129.000000
Skoda         38255.666667
Smart         22660.666667
Sono          25500.000000
Tesla         80272.307692
Volkswagen    34602.375000
Volvo         60437.000000

In [36]:
Cars_speed = Cars[(Cars['PriceEuro'] > 50000) & (Cars['TopSpeed_KmH'] > 200)].reset_index(drop=True)
Cars_speed

# Сделайте срез по столбцу PriceEuro со значениями более 50000 и по столбцу TopSpeed_KmH со значениями более 200.
# Переназначьте индексы таблицы начиная с нуля.
# Сохраните результаты проделанных действий в датафрейм с именем Cars_speed.


Brand                           Model  AccelSec  TopSpeed_KmH  \
0      Tesla    Model 3 Long Range Dual Motor       4.6           233   
1   Polestar                                2       4.7           210   
2      Lucid                             Air        2.8           250   
3    Porsche                   Taycan Turbo S       2.8           260   
4      Tesla    Model Y Long Range Dual Motor       5.1           217   
5       Audi                       e-tron GT        3.5           240   
6      Tesla   Model 3 Long Range Performance       3.4           261   
7      Tesla             Cybertruck Tri Motor       3.0           210   
8      Tesla               Model S Long Range       3.8           250   
9    Porsche                        Taycan 4S       4.0           250   
10     Tesla                        Roadster        2.1           410   
11     Tesla               Model X Long Range       4.6           250   
12     Tesla              Model S Performance       2.5           261   
13     Tesla   Model Y Long Range Performance       3.7           241   
14   Porsche                   Taycan 4S Plus       4.0           250   
15   Porsche            Taycan Cross Turismo        3.5           250   
16   Porsche                     Taycan Turbo       3.2           260   
17     Tesla              Model X Performance       2.8           250   
18      Audi              e-tron S 55 quattro       4.5           210   
19      Audi    e-tron S Sportback 55 quattro       4.5           210   

    Range_Km  Efficiency_WhKm FastCharge_KmH RapidCharge PowerTrain  \
0        450              161            940         Yes        AWD   
1        400              181            620         Yes        AWD   
2        610              180            620         Yes        AWD   
3        375              223            780         Yes        AWD   
4        425              171            930         Yes        AWD   
5        425              197            850         Yes        AWD   
6        435              167            910         Yes        AWD   
7        750              267            710         Yes        AWD   
8        515              184            560         Yes        AWD   
9        365              195            730         Yes        AWD   
10       970              206            920         Yes        AWD   
11       450              211            490         Yes        AWD   
12       505              188            550         Yes        AWD   
13       410              177            900         Yes        AWD   
14       425              197            890         Yes        AWD   
15       385              217            770         Yes        AWD   
16       390              215            810         Yes        AWD   
17       440              216            480         Yes        AWD   
18       320              270            510         Yes        AWD   
19       335              258            540         Yes        AWD   

      PlugType BodyStyle Segment  Seats  PriceEuro  
0   Type 2 CCS     Sedan       D      5      55480  
1   Type 2 CCS  Liftback       D      5      56440  
2   Type 2 CCS     Sedan       F      5     105000  
3   Type 2 CCS     Sedan       F      4     180781  
4   Type 2 CCS       SUV       D      7      58620  
5   Type 2 CCS     Sedan       F      4     125000  
6   Type 2 CCS     Sedan       D      5      61480  
7   Type 2 CCS    Pickup       N      6      75000  
8       Type 2  Liftback       F      5      79990  
9   Type 2 CCS     Sedan       F      4     102945  
10  Type 2 CCS    Cabrio       S      4     215000  
11      Type 2       SUV       F      7      85990  
12      Type 2  Liftback       F      5      96990  
13  Type 2 CCS       SUV       D      7      65620  
14  Type 2 CCS     Sedan       F      4     109302  
15  Type 2 CCS   Station       F      4     150000  
16  Type 2 CCS     Sedan       F      4     148301  
17      Type 2       SUV    