In [1]:
import pandas as pd
import numpy as np

In [7]:
arr1 = np.array((18, 14, 23, 36))
arr2 = np.array((12, 1, 4, 7))

In [12]:
np.add(arr1, arr2)

array([30, 15, 27, 43])

In [14]:
np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.array([1, 2, 3, 4, 5, 6]).reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [42]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'New York', 'Houston']
}

# Create DataFrame
df = pd.DataFrame(data)

In [35]:
df['Age'].unique()

array([25, 30, 35, 40])

In [45]:
aggregated = df.groupby('City').agg({'Age': ['mean', 'sum', 'std', 'prod', 'count']})
print(aggregated)

              Age                         
             mean sum       std prod count
City                                      
Houston      40.0  40       NaN   40     1
Los Angeles  30.0  30       NaN   30     1
New York     30.0  60  7.071068  875     2


In [44]:
25*35

875

In [25]:
type(df['Age'].unique())

numpy.ndarray

In [18]:
np.array([1, 2, 3, 4, 5, 6]).reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
arr1 + arr2

array([30, 15, 27, 43])

In [11]:
sum(arr1, arr2)

array([103,  92,  95,  98])

In [2]:
type(np.array([18, 14, 23, 36]))

numpy.ndarray

In [5]:
type(np.array((18, 14, 23, 36)))

numpy.ndarray