In [42]:
import numpy as np

# Random matrix

In [43]:
np.random.seed(42)
A = np.random.randint(0, 11, (3, 3))
B = np.random.randint(0, 11, (3, 3))

In [44]:
A

array([[ 6,  3, 10],
       [ 7,  4,  6],
       [ 9,  2,  6]])

In [45]:
B

array([[10, 10,  7],
       [ 4,  3,  7],
       [ 7,  2,  5]])

# Sum and dot product

In [46]:
print("Сумма", A + B)
print("\n")
print("Произведение", np.dot(A, B))

Сумма [[16 13 17]
 [11  7 13]
 [16  4 11]]


Произведение [[142  89 113]
 [128  94 107]
 [140 108 107]]


# Determinant

In [47]:
print("Определитель матрицы A:", np.linalg.det(A))

Определитель матрицы A: -112.00000000000006


# Inverse matrix

In [48]:
print("Обратная матрица:")
print(np.linalg.inv(A))

Обратная матрица:
[[-0.10714286 -0.01785714  0.19642857]
 [-0.10714286  0.48214286 -0.30357143]
 [ 0.19642857 -0.13392857 -0.02678571]]
